### ISSUE TITLE
Disallow the use of console

### ISSUE THREAD

**Issue by ahnwarez** [horoeka-2021/gardenz#12]
CI/CD should disallow any console logs/errors when code is pushed to the `main` or `dev` branchs.

The only console.log allowed should be in the `server/index.js` module when the server starts by adding this line at the top of the console.log.
```js
// eslint-disable-next-line
```

**Comment by tommy-yoon** [comment]
I found two options we can decide
1. The simplest: using a simple, one line linting rule enforces no console log - this will throw an error during linting
2. More sophisticated way to control logging: e.g. use external package to control logging

**Comment by tommy-yoon** [comment]
We will go with the linting
And it should be outside not in the package.json as it should be controlled by the CI/CD workflow

**Comment by tommy-yoon** [comment]
As it depends on the CI/CD workflow, I am putting this on pending for now

**Comment by tommy-yoon** [comment]
This is working now thanks to the below lines in ci.yml

 - name: Linting
        run: "npm run lint -- --rule 'no-console: 2'"

However, due to its dependency on #5 it is hard to see the result.
So, I guess #5 and #12 should be handled together
